### PR TITLE
Change default TTL from 86400 to 600.

### PR DESCRIPTION
**Pull request by marcus-foobar**

### CODE REVIEW

**Comment by acalm** [comment]
That's quite a decrease of the default TTL for the zone, is this something we want? Wouldn't it be better to specify lower TTL in the data using the template, like the zone in bonk?

It's not a breaking change and I don't really oppose it as such, it just seems weird.

**Comment by marcus-foobar** [comment]
It's the default TTL we want for all zones if we've not specified the TTL. If the change is made here or in a default template that is applied, it does not matter.

**Comment by dhozac** [comment]
This should be the default from the specification/server implementation, which is 1 day.

I guess some sort of configuration in the configuration file wouldn't be too ugly for this, but setting the default TTL to something unreasonably short like 600 shouldn't happen.

**Comment by acalm** [comment]
Looking at the [datamodel](https://github.com/dhozac/bonk/blob/master/DATAMODEL.md#dns-zones) dns zones have a TTL attribute, is there something weird that prevents setting the TTL to something default on input or changing an already set zone TTL to something different or am I missing something here? 
I think it might be a disservice to ones future self relying on the defaults in a template of a script dumping out bind specific zone files. For example, if bind is replaced and another script will have to generate files or (more likely) the default value in the template is changed to something else by another pull request because it sounded reasonable at the time, expected ttls will be ..unexpected? Of course nothing big, but annoying.

**Pull request closed without merging**
